export default function HomePage() {
    return (
        <>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
            <div>Home page</div>
        </>
    );
}
